### ISSUE TITLE
Serializer state transition bug

### ISSUE THREAD

**Issue by io7m** [io7m/smf#34]
Serializing metadata fails for both the text and binary formats:

```
smf: Main: ERROR: Cannot transition between the given states.
  Current state:   STATE_DATA_METADATA_FINISHED
  Requested state: STATE_DATA_METADATA_IN_PROGRESS

com.io7m.jfsm.core.FSMTransitionException: Cannot transition between the given states.
  Current state:   STATE_DATA_METADATA_FINISHED
  Requested state: STATE_DATA_METADATA_IN_PROGRESS

	at com.io7m.jfsm.core.FSMEnumMutable.transition(FSMEnumMutable.java:99)
	at com.io7m.smfj.format.text.SMFTV1Serializer.serializeMetadata(SMFTV1Serializer.java:705)
	at com.io7m.smfj.processing.api.SMFMemoryMeshSerializer.serialize(SMFMemoryMeshSerializer.java:94)
	at com.io7m.smfj.cmdline.Main$CommandFilter.call(Main.java:407)
	at com.io7m.smfj.cmdline.Main$CommandFilter.call(Main.java:294)
	at com.io7m.smfj.cmdline.Main.run(Main.java:142)
	at com.io7m.smfj.cmdline.Main.main(Main.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

Why have the unit tests not detected this error?

**Comment by io7m** [comment]
This actually turned out to be a bug in a not-yet-committed filter command. In order to prevent any occurrences of this happening in the future, new preconditions were added to the memory mesh type.
